### ISSUE TITLE
Make the XDT editable

### ISSUE THREAD

**Issue by davidebbo** [shibayan/IISManager#2]
Currently, the config is editable, and the xdt gets generated and is read-only. Now, for extra flexibility, consider the possibility of making both sides editable. e.g.

- User starts on config file, and makes some changes
- They switch to XDT tab, and you calculate the XDT (no change from today)
- Now let's say they tweak the XDT directly. The minute this happens, you start treating the XDT as the 'master data', even if they don't save it
- They switch back to the Config tab. Now you just need to apply the XDT to the base config. It's the same thing that you already do in `GetCurrentConfig()`, except that the XDT may not be saved, so you have to pass it (similar to what you do now for GenerateXdt(), except the reverse).

Conceptually, the two transforms are:

- When switching to XDT tab: `XDT=CONFIG-BASE` (FatAntelope)
- When switching to CONFIG tab: `CONFIG=BASE+XDT` (regular XDT transform engine)

This opens some interesting user scenarios. e.g. maybe user wants to start from an [XDT sample](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples), but then make additional tweaks directly to the config. So you get to edit whichever side is more convenient, and it works in both cases.

**Comment by shibayan** [comment]
That's right! I also began a modified using the XDT sample. It's a great improvement idea!
Enable editing in the XDT editor tab :)

**Comment by shibayan** [comment]
@davidebbo I released IIS Manager 1.0.3 in Site Extension Gallery
This version include XDT editable feature. It can add a XDT samples easily. :smile: 

Thank you for a very great idea!

**Comment by davidebbo** [comment]
Well done, it works very well! This is an awesome extension.
