### ISSUE TITLE
After install, the route is not able to start the IIS manager

### ISSUE THREAD

**Issue by bartdekeersmaeker** [shibayan/IISManager#5]
"No route registered for '/IISManager/'"

**Comment by shibayan** [comment]
Hello. Please restart a Kudu.

**Comment by bartdekeersmaeker** [comment]
Oh, I see, thanks.
I did an install from within azure portal itself, than it is working fine.
But thanks for the restart tip anyway !

**Comment by bartdekeersmaeker** [comment]
Oh, but once installed, the URL throws another error
"You do not have permission to view this directory or page."
